/**
 * Sample Rosters for NNLL Minor AAA
 */

export const SAMPLE_TEAMS = [
  {
    teamId: 'team-black-bats-6589',
    teamName: 'Black Bats',
    division: 'Minor AAA',
    season: 'Spring 2026',
    headCoach: 'Coach Collins',
    adminEmail: 'mcollinswork6@gmail.com',
    opponentName: 'River Cats',
    createdAt: '2026-10-02T23:03:06.589Z',
    playerCount: 12,
    players: [
      { id: 'p_1790982212236', jersey: 33, jerseyNumber: 33, firstName: 'Elias', lastName: 'Collins', name: 'Elias Collins', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Elias', 'Player Last name': 'Collins', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p_1790982225041', jersey: 5, jerseyNumber: 5, firstName: 'Hunter', lastName: 'Huston', name: 'Hunter Huston', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Hunter', 'Player Last name': 'Huston', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p_1790982297765', jersey: 10, jerseyNumber: 10, firstName: 'Jason', lastName: 'Clark Jr.', name: 'Jason Clark Jr.', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Jason', 'Player Last name': 'Clark Jr.', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p_1790982316295', jersey: 12, jerseyNumber: 12, firstName: 'Larry', lastName: 'Parsons', name: 'Larry Parsons', age: 11, 'Player Age': 11, canPitch: true, canCatch: true, 'Player First Name': 'Larry', 'Player Last name': 'Parsons', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p_1790982338861', jersey: 8, jerseyNumber: 8, firstName: 'Kenton', lastName: 'Lassen', name: 'Kenton Lassen', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Kenton', 'Player Last name': 'Lassen', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p_1790982359546', jersey: 21, jerseyNumber: 21, firstName: 'Mason', lastName: 'Kaine', name: 'Mason Kaine', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Mason', 'Player Last name': 'Kaine', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p_1790982389667', jersey: 7, jerseyNumber: 7, firstName: 'Calan', lastName: 'Burley', name: 'Calan Burley', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Calan', 'Player Last name': 'Burley', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p_1790982406463', jersey: 4, jerseyNumber: 4, firstName: 'Drew', lastName: 'Bluford', name: 'Drew Bluford', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Drew', 'Player Last name': 'Bluford', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p_1790982434699', jersey: 15, jerseyNumber: 15, firstName: 'Jameson', lastName: 'Parker', name: 'Jameson Parker', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Jameson', 'Player Last name': 'Parker', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p_1790982488516', jersey: 18, jerseyNumber: 18, firstName: 'Cody', lastName: 'Byler', name: 'Cody Byler', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Cody', 'Player Last name': 'Byler', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'p_1790982521107', jersey: 30, jerseyNumber: 30, firstName: 'Elijah', lastName: 'Stewart', name: 'Elijah Stewart', age: 11, 'Player Age': 11, canPitch: false, canCatch: false, 'Player First Name': 'Elijah', 'Player Last name': 'Stewart', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p_1790982573378', jersey: 9, jerseyNumber: 9, firstName: 'Israel', lastName: 'Iyere', name: 'Israel Iyere', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Israel', 'Player Last name': 'Iyere', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
    ],
  },
  {
    teamId: 'nnll-rivercats-11',
    teamName: 'River Cats (11 Players)',
    opponentName: 'Black Bats',
    players: [
      { id: 'p1', jersey: 2, jerseyNumber: 2, firstName: 'Liam', lastName: 'Garcia', name: 'Liam Garcia', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Liam', 'Player Last name': 'Garcia', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p2', jersey: 5, jerseyNumber: 5, firstName: 'Noah', lastName: 'Davis', name: 'Noah Davis', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Noah', 'Player Last name': 'Davis', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'p3', jersey: 7, jerseyNumber: 7, firstName: 'Mason', lastName: 'Miller', name: 'Mason Miller', age: 11, 'Player Age': 11, canPitch: true, canCatch: true, 'Player First Name': 'Mason', 'Player Last name': 'Miller', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'p4', jersey: 9, jerseyNumber: 9, firstName: 'Lucas', lastName: 'Wilson', name: 'Lucas Wilson', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Lucas', 'Player Last name': 'Wilson', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p5', jersey: 11, jerseyNumber: 11, firstName: 'Oliver', lastName: 'Martinez', name: 'Oliver Martinez', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Oliver', 'Player Last name': 'Martinez', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'p6', jersey: 14, jerseyNumber: 14, firstName: 'Elijah', lastName: 'Taylor', name: 'Elijah Taylor', age: 10, 'Player Age': 10, canPitch: false, canCatch: true, 'Player First Name': 'Elijah', 'Player Last name': 'Taylor', 'Can Pitch flag': false, 'can catch flag': true, eligiblePositions: { canPitch: false, canCatch: true } },
      { id: 'p7', jersey: 18, jerseyNumber: 18, firstName: 'James', lastName: 'Anderson', name: 'James Anderson', age: 10, 'Player Age': 10, canPitch: false, canCatch: false, 'Player First Name': 'James', 'Player Last name': 'Anderson', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p8', jersey: 22, jerseyNumber: 22, firstName: 'Benjamin', lastName: 'Thomas', name: 'Benjamin Thomas', age: 11, 'Player Age': 11, canPitch: true, canCatch: false, 'Player First Name': 'Benjamin', 'Player Last name': 'Thomas', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'p9', jersey: 27, jerseyNumber: 27, firstName: 'Henry', lastName: 'White', name: 'Henry White', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Henry', 'Player Last name': 'White', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p10', jersey: 33, jerseyNumber: 33, firstName: 'Alexander', lastName: 'Harris', name: 'Alexander Harris', age: 10, 'Player Age': 10, canPitch: false, canCatch: false, 'Player First Name': 'Alexander', 'Player Last name': 'Harris', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'p11', jersey: 42, jerseyNumber: 42, firstName: 'Jackson', lastName: 'Clark', name: 'Jackson Clark', age: 11, 'Player Age': 11, canPitch: true, canCatch: true, 'Player First Name': 'Jackson', 'Player Last name': 'Clark', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
    ],
  },
  {
    teamId: 'nnll-giants-12',
    teamName: 'Giants (12 Players)',
    opponentName: 'River Cats',
    players: [
      { id: 'g1', jersey: 1, jerseyNumber: 1, firstName: 'Ethan', lastName: 'Walker', name: 'Ethan Walker', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Ethan', 'Player Last name': 'Walker', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'g2', jersey: 3, jerseyNumber: 3, firstName: 'Logan', lastName: 'Hall', name: 'Logan Hall', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Logan', 'Player Last name': 'Hall', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'g3', jersey: 4, jerseyNumber: 4, firstName: 'Jacob', lastName: 'Allen', name: 'Jacob Allen', age: 9, 'Player Age': 9, canPitch: false, canCatch: true, 'Player First Name': 'Jacob', 'Player Last name': 'Allen', 'Can Pitch flag': false, 'can catch flag': true, eligiblePositions: { canPitch: false, canCatch: true } },
      { id: 'g4', jersey: 8, jerseyNumber: 8, firstName: 'Michael', lastName: 'Young', name: 'Michael Young', age: 11, 'Player Age': 11, canPitch: true, canCatch: false, 'Player First Name': 'Michael', 'Player Last name': 'Young', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'g5', jersey: 10, jerseyNumber: 10, firstName: 'Daniel', lastName: 'King', name: 'Daniel King', age: 10, 'Player Age': 10, canPitch: false, canCatch: false, 'Player First Name': 'Daniel', 'Player Last name': 'King', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'g6', jersey: 12, jerseyNumber: 12, firstName: 'Matthew', lastName: 'Wright', name: 'Matthew Wright', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Matthew', 'Player Last name': 'Wright', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'g7', jersey: 15, jerseyNumber: 15, firstName: 'Samuel', lastName: 'Scott', name: 'Samuel Scott', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Samuel', 'Player Last name': 'Scott', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'g8', jersey: 20, jerseyNumber: 20, firstName: 'David', lastName: 'Green', name: 'David Green', age: 10, 'Player Age': 10, canPitch: false, canCatch: false, 'Player First Name': 'David', 'Player Last name': 'Green', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'g9', jersey: 23, jerseyNumber: 23, firstName: 'Joseph', lastName: 'Adams', name: 'Joseph Adams', age: 11, 'Player Age': 11, canPitch: true, canCatch: false, 'Player First Name': 'Joseph', 'Player Last name': 'Adams', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'g10', jersey: 25, jerseyNumber: 25, firstName: 'Carter', lastName: 'Baker', name: 'Carter Baker', age: 10, 'Player Age': 10, canPitch: false, canCatch: true, 'Player First Name': 'Carter', 'Player Last name': 'Baker', 'Can Pitch flag': false, 'can catch flag': true, eligiblePositions: { canPitch: false, canCatch: true } },
      { id: 'g11', jersey: 30, jerseyNumber: 30, firstName: 'Owen', lastName: 'Nelson', name: 'Owen Nelson', age: 10, 'Player Age': 10, canPitch: false, canCatch: false, 'Player First Name': 'Owen', 'Player Last name': 'Nelson', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'g12', jersey: 99, jerseyNumber: 99, firstName: 'Wyatt', lastName: 'Carter', name: 'Wyatt Carter', age: 11, 'Player Age': 11, canPitch: true, canCatch: false, 'Player First Name': 'Wyatt', 'Player Last name': 'Carter', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
    ],
  },
  {
    teamId: 'nnll-athletics-9',
    teamName: 'Athletics (9 Players)',
    opponentName: 'Thunder',
    players: [
      { id: 'a1', jersey: 2, jerseyNumber: 2, firstName: 'Aiden', lastName: 'Mitchell', name: 'Aiden Mitchell', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Aiden', 'Player Last name': 'Mitchell', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'a2', jersey: 6, jerseyNumber: 6, firstName: 'Gabriel', lastName: 'Perez', name: 'Gabriel Perez', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Gabriel', 'Player Last name': 'Perez', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'a3', jersey: 10, jerseyNumber: 10, firstName: 'Julian', lastName: 'Roberts', name: 'Julian Roberts', age: 11, 'Player Age': 11, canPitch: true, canCatch: true, 'Player First Name': 'Julian', 'Player Last name': 'Roberts', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'a4', jersey: 13, jerseyNumber: 13, firstName: 'Anthony', lastName: 'Turner', name: 'Anthony Turner', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Anthony', 'Player Last name': 'Turner', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'a5', jersey: 17, jerseyNumber: 17, firstName: 'Dylan', lastName: 'Phillips', name: 'Dylan Phillips', age: 10, 'Player Age': 10, canPitch: false, canCatch: true, 'Player First Name': 'Dylan', 'Player Last name': 'Phillips', 'Can Pitch flag': false, 'can catch flag': true, eligiblePositions: { canPitch: false, canCatch: true } },
      { id: 'a6', jersey: 21, jerseyNumber: 21, firstName: 'Leo', lastName: 'Campbell', name: 'Leo Campbell', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Leo', 'Player Last name': 'Campbell', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'a7', jersey: 24, jerseyNumber: 24, firstName: 'Caleb', lastName: 'Parker', name: 'Caleb Parker', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Caleb', 'Player Last name': 'Parker', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'a8', jersey: 28, jerseyNumber: 28, firstName: 'Ryan', lastName: 'Evans', name: 'Ryan Evans', age: 10, 'Player Age': 10, canPitch: false, canCatch: false, 'Player First Name': 'Ryan', 'Player Last name': 'Evans', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'a9', jersey: 35, jerseyNumber: 35, firstName: 'Luke', lastName: 'Edwards', name: 'Luke Edwards', age: 11, 'Player Age': 11, canPitch: true, canCatch: false, 'Player First Name': 'Luke', 'Player Last name': 'Edwards', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
    ],
  },
  {
    teamId: 'nnll-mudcats-8',
    teamName: 'Mudcats (8 Players - Min Short Team)',
    opponentName: 'IronBirds',
    players: [
      { id: 'm1', jersey: 3, jerseyNumber: 3, firstName: 'Hunter', lastName: 'Collins', name: 'Hunter Collins', age: 10, 'Player Age': 10, canPitch: true, canCatch: true, 'Player First Name': 'Hunter', 'Player Last name': 'Collins', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'm2', jersey: 7, jerseyNumber: 7, firstName: 'Eli', lastName: 'Stewart', name: 'Eli Stewart', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Eli', 'Player Last name': 'Stewart', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'm3', jersey: 11, jerseyNumber: 11, firstName: 'Connor', lastName: 'Sanchez', name: 'Connor Sanchez', age: 11, 'Player Age': 11, canPitch: true, canCatch: true, 'Player First Name': 'Connor', 'Player Last name': 'Sanchez', 'Can Pitch flag': true, 'can catch flag': true, eligiblePositions: { canPitch: true, canCatch: true } },
      { id: 'm4', jersey: 16, jerseyNumber: 16, firstName: 'Aaron', lastName: 'Morris', name: 'Aaron Morris', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Aaron', 'Player Last name': 'Morris', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'm5', jersey: 19, jerseyNumber: 19, firstName: 'Christian', lastName: 'Rogers', name: 'Christian Rogers', age: 10, 'Player Age': 10, canPitch: false, canCatch: true, 'Player First Name': 'Christian', 'Player Last name': 'Rogers', 'Can Pitch flag': false, 'can catch flag': true, eligiblePositions: { canPitch: false, canCatch: true } },
      { id: 'm6', jersey: 23, jerseyNumber: 23, firstName: 'Landon', lastName: 'Reed', name: 'Landon Reed', age: 10, 'Player Age': 10, canPitch: true, canCatch: false, 'Player First Name': 'Landon', 'Player Last name': 'Reed', 'Can Pitch flag': true, 'can catch flag': false, eligiblePositions: { canPitch: true, canCatch: false } },
      { id: 'm7', jersey: 31, jerseyNumber: 31, firstName: 'Jonathan', lastName: 'Cook', name: 'Jonathan Cook', age: 9, 'Player Age': 9, canPitch: false, canCatch: false, 'Player First Name': 'Jonathan', 'Player Last name': 'Cook', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
      { id: 'm8', jersey: 44, jerseyNumber: 44, firstName: 'Nolan', lastName: 'Morgan', name: 'Nolan Morgan', age: 11, 'Player Age': 11, canPitch: false, canCatch: false, 'Player First Name': 'Nolan', 'Player Last name': 'Morgan', 'Can Pitch flag': false, 'can catch flag': false, eligiblePositions: { canPitch: false, canCatch: false } },
    ],
  },
];
