/**
 * Sample Rosters for NNLL Minor AAA
 */

export const SAMPLE_TEAMS = [
  {
    teamId: 'team-black-bats-6589',
    teamName: 'Black Bats',
    division: 'Minor AAA',
    season: 'Spring 2026',
    headCoach: 'Coach Collins',
    adminEmail: 'mcollinswork6@gmail.com',
    opponentName: 'River Cats',
    createdAt: '2026-10-02T23:03:06.589Z',
    playerCount: 12,
    players: [
      { id: 'p_1790982212236', name: 'Elias Collins', jerseyNumber: 33, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'p_1790982225041', name: 'Hunter Huston', jerseyNumber: 5, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'p_1790982297765', name: 'Jason Clark Jr.', jerseyNumber: 10, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'p_1790982316295', name: 'Larry Parsons', jerseyNumber: 12, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'p_1790982338861', name: 'Kenton Lassen', jerseyNumber: 8, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: true } },
      { id: 'p_1790982359546', name: 'Mason Kaine', jerseyNumber: 21, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'p_1790982389667', name: 'Calan Burley', jerseyNumber: 7, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'p_1790982406463', name: 'Drew Bluford', jerseyNumber: 4, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: false } },
      { id: 'p_1790982434699', name: 'Jameson Parker', jerseyNumber: 15, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'p_1790982488516', name: 'Cody Byler', jerseyNumber: 18, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: false } },
      { id: 'p_1790982521107', name: 'Elijah Stewart', jerseyNumber: 30, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'p_1790982573378', name: 'Israel Iyere', jerseyNumber: 9, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
    ],
  },
  {
    teamId: 'nnll-rivercats-11',
    teamName: 'River Cats (11 Players)',
    opponentName: 'Black Bats',
    players: [
      { id: 'p1', name: 'Liam Garcia', jerseyNumber: 2, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'p2', name: 'Noah Davis', jerseyNumber: 5, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
      { id: 'p3', name: 'Mason Miller', jerseyNumber: 7, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: false } },
      { id: 'p4', name: 'Lucas Wilson', jerseyNumber: 9, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: true } },
      { id: 'p5', name: 'Oliver Martinez', jerseyNumber: 11, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: false } },
      { id: 'p6', name: 'Elijah Taylor', jerseyNumber: 14, eligiblePositions: { canPitch: false, canCatch: true, canPlayFirstBase: false } },
      { id: 'p7', name: 'James Anderson', jerseyNumber: 18, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'p8', name: 'Benjamin Thomas', jerseyNumber: 22, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
      { id: 'p9', name: 'Henry White', jerseyNumber: 27, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'p10', name: 'Alexander Harris', jerseyNumber: 33, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'p11', name: 'Jackson Clark', jerseyNumber: 42, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
    ],
  },
  {
    teamId: 'nnll-giants-12',
    teamName: 'Giants (12 Players)',
    opponentName: 'River Cats',
    players: [
      { id: 'g1', name: 'Ethan Walker', jerseyNumber: 1, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'g2', name: 'Logan Hall', jerseyNumber: 3, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
      { id: 'g3', name: 'Jacob Allen', jerseyNumber: 4, eligiblePositions: { canPitch: false, canCatch: true, canPlayFirstBase: false } },
      { id: 'g4', name: 'Michael Young', jerseyNumber: 8, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: false } },
      { id: 'g5', name: 'Daniel King', jerseyNumber: 10, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: true } },
      { id: 'g6', name: 'Matthew Wright', jerseyNumber: 12, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: false } },
      { id: 'g7', name: 'Samuel Scott', jerseyNumber: 15, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'g8', name: 'David Green', jerseyNumber: 20, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'g9', name: 'Joseph Adams', jerseyNumber: 23, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
      { id: 'g10', name: 'Carter Baker', jerseyNumber: 25, eligiblePositions: { canPitch: false, canCatch: true, canPlayFirstBase: false } },
      { id: 'g11', name: 'Owen Nelson', jerseyNumber: 30, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'g12', name: 'Wyatt Carter', jerseyNumber: 99, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
    ],
  },
  {
    teamId: 'nnll-athletics-9',
    teamName: 'Athletics (9 Players)',
    opponentName: 'Thunder',
    players: [
      { id: 'a1', name: 'Aiden Mitchell', jerseyNumber: 2, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'a2', name: 'Gabriel Perez', jerseyNumber: 6, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
      { id: 'a3', name: 'Julian Roberts', jerseyNumber: 10, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: false } },
      { id: 'a4', name: 'Anthony Turner', jerseyNumber: 13, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: true } },
      { id: 'a5', name: 'Dylan Phillips', jerseyNumber: 17, eligiblePositions: { canPitch: false, canCatch: true, canPlayFirstBase: false } },
      { id: 'a6', name: 'Leo Campbell', jerseyNumber: 21, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: false } },
      { id: 'a7', name: 'Caleb Parker', jerseyNumber: 24, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'a8', name: 'Ryan Evans', jerseyNumber: 28, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'a9', name: 'Luke Edwards', jerseyNumber: 35, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
    ],
  },
  {
    teamId: 'nnll-mudcats-8',
    teamName: 'Mudcats (8 Players - Min Short Team)',
    opponentName: 'IronBirds',
    players: [
      { id: 'm1', name: 'Hunter Collins', jerseyNumber: 3, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: true } },
      { id: 'm2', name: 'Eli Stewart', jerseyNumber: 7, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: true } },
      { id: 'm3', name: 'Connor Sanchez', jerseyNumber: 11, eligiblePositions: { canPitch: true, canCatch: true, canPlayFirstBase: false } },
      { id: 'm4', name: 'Aaron Morris', jerseyNumber: 16, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: true } },
      { id: 'm5', name: 'Christian Rogers', jerseyNumber: 19, eligiblePositions: { canPitch: false, canCatch: true, canPlayFirstBase: false } },
      { id: 'm6', name: 'Landon Reed', jerseyNumber: 23, eligiblePositions: { canPitch: true, canCatch: false, canPlayFirstBase: false } },
      { id: 'm7', name: 'Jonathan Cook', jerseyNumber: 31, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
      { id: 'm8', name: 'Nolan Morgan', jerseyNumber: 44, eligiblePositions: { canPitch: false, canCatch: false, canPlayFirstBase: false } },
    ],
  },
];
